#!/bin/bash
# Filename:                cindercleaner
# Description:             cleans orphaned cinder volumes
# Supported Langauge(s):   Bash 4.x, Python 2.7.y
# Time-stamp:              <2015-09-06 15:32:33 jfulton> 
# See README.md at https://github.com/fultonj/cindercleaner
# -------------------------------------------------------
# This one-line wrapper just calls Red Hat SCL and Python virtenv 
allparams=${@} /usr/bin/scl enable python27 '/home/cindercleaner/venv/cindercleaner/bin/python cindercleaner.py $allparams'

